### ISSUE TITLE
fm35 data from 72208

### ISSUE THREAD

**Issue by rs1729** [mhaberler/radiosonde-datacollector#1]
On
https://radiosonde.mah.priv.at/app/
I downloaded fm35 data from station id 72208 (Charleston) in GeoJSON fromat.
Up to altitude 15km it looks ok, but in the stratosphere, when the temperature goes up again, there are several data points with "flags" 0x10000 and lower altitudes (gpheight) and suspicious temperatures. (Do you have a documentation for "flags"?)
Removing these temperatures at higher altitudes, it still doesn't look right, e.g. `72208_20220217_0000Z.json` compared to
http://weather.uwyo.edu/cgi-bin/bufrraob.py?datetime=2022-02-17%200:00:00&id=72208&type=TEXT:LIST
(Observations for Station 72208 starting 2307Z 16 Feb 2022)

Starting time matches "firstSeen" below, accept for the date, seems to be off by one day? (The sounding 2022-02-18 00Z would start at 2303Z 17 Feb 2022.)
The "time" is a bit confusing, or maybe it is just the date?
72208_20220217_0000Z.json
shows
`"syn_timestamp": 1645056000 = 2022-02-17 00:00:00 UTC`
however
`"firstSeen": 1645139220 = 2022-02-17 23:07:00 UTC`
and the data points start at this timestamp
```
2022-02-17 23:07:00 UTC
2022-02-17 23:07:28 UTC
2022-02-17 23:07:38 UTC
2022-02-17 23:07:46 UTC
2022-02-17 23:08:03 UTC
2022-02-17 23:08:34 UTC
[...]
2022-02-17 23:55:21 UTC
2022-02-17 23:56:10 UTC
2022-02-18 00:01:22 UTC
2022-02-17 23:58:39 UTC
2022-02-17 23:59:37 UTC
2022-02-18 00:01:48 UTC
2022-02-18 00:02:41 UTC
2022-02-18 00:03:25 UTC
2022-02-18 00:09:44 UTC
2022-02-18 00:04:48 UTC
2022-02-18 00:05:02 UTC
2022-02-18 00:06:35 UTC
2022-02-18 00:06:39 UTC
2022-02-18 00:07:27 UTC
2022-02-18 00:08:16 UTC
2022-02-18 00:16:27 UTC
2022-02-18 00:10:08 UTC
[...]
2022-02-18 00:35:42 UTC
2022-02-18 00:37:03 UTC
2022-02-18 00:39:44 UTC
2022-02-18 00:39:44 UTC
```
Is this already in the source file `20220217_0000.gz`?

**Comment by mhaberler** [comment]
Hi @rs1729 !
the flags are documented here:  https://github.com/mhaberler/radiosonde-datacollector/blob/dev/config.py#L141-L161

I'm currently traveling and back Sun evening, will look into your question in detail and respond

**Comment by rs1729** [comment]
Thanks! And no problem, no hurry.
I suspect firstSeen or takeoff time is +1 day in fm35-geojson because the sounding starts before midnight? And then the deltas are added? (At least that's what happened to me once when processing TTAA messages...)

It's only for fm35 data, for
Station: Va Blacksburg KRNK (WMO id: 72318)
you have both datasets,
```
format: fm35/netCDF
Synoptic time: 2022-02-19 00:00Z (9 hours old)
First seen: 2022-02-19 23:04Z
"syn_timestamp": 1645228800,
"firstSeen": 1645311840,
```
```
format: fm94/BUFR
Synoptic time: 2022-02-19 00:00Z (8.9 hours old)
First seen: 2022-02-18 23:04Z
"syn_timestamp": 1645228800,
"firstSeen": 1645225449,
```
fm94/BUFR is correct.


(btw: In the CSV download there seem to be no line breaks? That's ok for JSON, but for CSV it makes it difficult to read in an editor.)

**Comment by mhaberler** [comment]
ok, got to look at this  - thanks for drilling!

you are spot on, the timestamps of fm35 paths seem to be off as you described

first to drill down on the source file:

your best bet is to use the https://www.windy.com/plugins/windy-plugin-radiosonde plugin and look at the station detail (things are in transition and the radiosonde.mah.priv.at apps are pretty much broken ATM)

you can also download the source file from there (20220217_0000.gz) - this is a netCDF file usually containing reports for several stations.

Unzip, and run `ncdump 20220217_0000` which gives you a json format dump of the contents, among them the timestamps property.

the issue is very likely in the [simulated path code](https://github.com/mhaberler/radiosonde-datacollector/blob/dev/netcdfutil.py#L365-L383) which manipulates the timestamps

now that path simulation is a hack to start with, and I might well have bugs in there - I put it in place to get a rough drift indication for the fm35-only reporting stations (which unfortunately includes pretty much all of the US)

frankly I hope we get past this by either disabling path simulation or taking out the fm35 processing altogether because it is way outdated, and the US and a few developing countries are the last holdouts - for quality data fm94 is the only option

I'll look into this - not promising a quick fix though

**Comment by mhaberler** [comment]
> (btw: In the CSV download there seem to be no line breaks? That's ok for JSON, but for CSV it makes it difficult to read in an editor.)

The CSV file is newline-terminate; is this really an issue? (are you using Windows?)

**Comment by mhaberler** [comment]
> On https://radiosonde.mah.priv.at/app/ I downloaded fm35 data from station id 72208 (Charleston) in GeoJSON fromat. Up to altitude 15km it looks ok, but in the stratosphere, when the temperature goes up again, there are several data points with "flags" 0x10000 and lower altitudes (gpheight) and suspicious temperatures. (Do you have a documentation for "flags"?) Removing these temperatures at higher altitudes, it still doesn't look right, e.g. `72208_20220217_0000Z.json` compared to http://weather.uwyo.edu/cgi-bin/bufrraob.py?datetime=2022-02-17%200:00:00&id=72208&type=TEXT:LIST (Observations for Station 72208 starting 2307Z 16 Feb 2022)

I'd be really interested to find an ascent where we have both fm35 and fm94 and there are significant differences

**Comment by rs1729** [comment]
> > (btw: In the CSV download there seem to be no line breaks? That's ok for JSON, but for CSV it makes it difficult to read in an editor.)
> 
> The CSV file is newline-terminate; is this really an issue? (are you using Windows?)

Not Windows, Linux.
After downloading there are no line breaks, all in one line. Don't know if it's the browser (firefox), but why would it filter the line breaks, hm...
The JSON downloads are without line breaks as well, but for JSON it doesn't matter, can be formatted afterwards and saves some bytes.

**Comment by mhaberler** [comment]
using Chrome/MacOS here

here are two downloads re-uploaded, those do have line breaks:

https://static.mah.priv.at/cors/16045_20210425_110000.geojson
https://static.mah.priv.at/public/54662_20220224_1200Z.csv

**Comment by rs1729** [comment]
> > On https://radiosonde.mah.priv.at/app/ I downloaded fm35 data from station id 72208 (Charleston) in GeoJSON fromat. Up to altitude 15km it looks ok, but in the stratosphere, when the temperature goes up again, there are several data points with
 
> I'd be really interested to find an ascent where we have both fm35 and fm94 and there are significant differences

I have only used the downloads on  https://radiosonde.mah.priv.at/app/.
Station: Blacksburg, Va - KRNK (WMO id: 72318)
has fm35 and fm94, look at the 00Z soundings.
The source files (netCF or bufr) have no download link.

fm35:
Synoptic time: 2022-02-24 00:00Z (14.3 hours old)
First seen: 2022-02-24 23:03Z
72318_20220224_0000Z-fm35.json, first JSON timestamp:
```
            "properties": {
                "pressure": 946,
                "dewpoint": 281.75,
                "temp": 288.75,
                "gpheight": 639,
                "flags": 196608,
                "time": 1645743780
            }
```

fm94:
Synoptic time: 2022-02-24 00:00Z (14.3 hours old)
First seen: 2022-02-23 23:03Z
72318_20220224_0000Z-fm94.json, first JSON timestamp:
```
            "properties": {
                "time": 1645657417,
                "gpheight": 639,
                "temp": 288.75,
                "dewpoint": 281.95,
                "pressure": 946.1,
                "wind_u": 2.85,
                "wind_v": -1.21,
                "flags": 145408
            }
```
"time" difference 86363 seconds, though the data points are approximately the same (fm34 has lower time resolution).

**Comment by mhaberler** [comment]
> I have only used the downloads on https://radiosonde.mah.priv.at/app/.

I see. 
Please give the downloads via windy.com/plugins/windy-plugin-radiosonde a try, different codebase.

Have not looked at /app branch in a year or so.

**Comment by rs1729** [comment]
> using Chrome/MacOS here
> 
> here are two downloads re-uploaded, those do have line breaks:
> 
> https://static.mah.priv.at/cors/16045_20210425_110000.geojson
https://static.mah.priv.at/public/54662_20220224_1200Z.csv

Here I see line breaks!

**Comment by mhaberler** [comment]
> The source files (netCF or bufr) have no download link.

try the windy radiosonde plugin. That has valid download links

**Comment by rs1729** [comment]
Ok, in windy I can download also the source file!
Not sure how to select between fm94 and fm35, I see only fm94 for Blacksburg 72318.
The selection of "Syn time" is a bit tricky...
The older(?) map (with stations only) looked a bit more light weight.
fm94 was ok,
only difference to the /app download is the last line
```
        "last_reference": 1645711493
```

If I look at Charleston WMO id: 72208 on windy:
```
Synoptic time: 2022-02-24 00:00Z (14.6 hours old)
First seen: 2022-02-24 23:06Z
```
and the timestamps in JSON are +24h.

Now I will look at the netCDF file.

**Comment by rs1729** [comment]
20220224_0000 nc file:
```
float64 synTime(recNum)
    long_name: Synoptic Time
synTime = 1645660800 = 2022-02-24 00:00:00 UTC
```
don't know if there are timestamps, there is 'relTime: Sounding Release Time' and 'invTime' (no long_name).
invTime has the same values as synTime. relTime are either 2022-02-24 23:xx... or 2012-01-01 00:00:00 UTC.
Don't see other time variables.

**Comment by mhaberler** [comment]
to see what is available for a given station, look at https://radiosonde.mah.priv.at/data/summary.geojson - the windy plugin does not show fm35's if a fm94 for the same synop time is available 

however those files are online

for instance the first station, 01004, you'll find

````
              "ascents": [
                    {
                        "syn_timestamp": 1645790400,
                        "repfmt": "fm94"
                    },
                    {
                        "syn_timestamp": 1645790400,
                        "repfmt": "fm35"
                    },

````

those two translate into 

[fm94](radiosonde.mah.priv.at/data/station/01/004/2022/02/fm94/01004_20220225_120000.geojson)
[fm35](radiosonde.mah.priv.at/data/station/01/004/[2](http://radiosonde.mah.priv.at/data/station/01/004/2022/02/fm94/10238_20220225_180000.geojson)022/02/fm35/01004_20220225_120000.geojson)

**Comment by rs1729** [comment]
Looked a bit more into the netCDF file, now I see it is the data for all stations. So netCDF/fm35 has the synoptic time and release time for each WMO station number, and station location. Then the observations for each station include wind velocity and geopotential height from which you calculate/integrate the flight path. But there is no timestamps, so you calculate the time into flight from diff_height/ascent_rate!?
(There is some zickzack at higher altitudes sometimes, maybe the data points are not in order in the netCDF source?)

Now the _release_ _time_ `relTime` is off by 24h already in the netCDF file, e.g.
```
WMO: 72318  SYN: 1645660800 = 2022-02-24 00:00:00 UTC  #  REL: 1645743780 = 2022-02-24 23:03:00 UTC
WMO: 72208  SYN: 1645660800 = 2022-02-24 00:00:00 UTC  #  REL: 1645743960 = 2022-02-24 23:06:00 UTC
```
seems like it does not consider that if the release/launch is before 00Z synoptic time, it is actually the previous day.
Thus starting at `takeoff = relTime` and then adding `sampleTime = takeoff + secsIntoFlight`, the timestamps are 24h into the future for midnight launches, if it is launched before midnight.

**Comment by mhaberler** [comment]
yes, the netCDF's typically carry a lot of stations in a single file (btw BUFR files also can contain several 'subsets' (= different ascents))

the path simulation is based on an assumed ascent rate. My meteo mentor suggested the typical ascent speed is around 5m/s. I did some analysis on BUFR files which do have timestamped elevations and I arrived at an average ascent speed of about 6.3m/s, which I use to [estimate the time between two fm35 elevations](https://github.com/mhaberler/radiosonde-datacollector/blob/dev/netcdfutil.py#L24-L26). That in turn is used to estimate the displacement based on the [average u and v vectors](https://github.com/mhaberler/radiosonde-datacollector/blob/dev/netcdfutil.py#L375-L376).

all this is rather empirical and ad-hoc, so not likely to give more than a general idea what the flight path was. And there might be errors in my assumptions as well as my code. 

stepping back a bit - I wish we could drop fm35 altogether and many areas of the world have decent fm94 coverage. But this transition is now over some 20 years underway, and still not completed - in particular the US, so we're limping along with the aforementioned hacks. 

A few days ago we added a feed from https://www.wis-jma.go.jp/cms/index.html which distributes only fm94 BUFR files. It turned out that some US stations inject BUFR's which are transcoded from fm35's and thus lack displacement data, hence are dropped in the QC step. It is the result of an aborted attempt to transition to fm94 and they fell back to this transcoding hack. So "BUFR" doesnt equal "has path data" either.

But it's not systematic either; there are a handful of US stations which report bona fide fm94's, like San Diego Miramar, Us (WMO id: 73033), Va Blacksburg KRNK (WMO id: 72318) and  Ak Fairbanks/Int. PAFA (WMO id: 70261).

This only scratches the surface of the mess of methods and data formats I encountered dealing with these meteo bureaucracies. If they had to earn their money by selling services, they'd be broke in no time flat. Some day I'll write up a blog post on this.

Thanks a lot for your accurate inspection and suggestion - I'll look into fixing this! 

I need to check if your observation is systematic or an intermittent error by some stations (my major maintenance job so far has been to catch corner cases in junk data coming in).

If you want to go straight to the source of all fm35's I receive: this is the lftp mirroring script I am using atm:

````
lftp  -u "anonymous,mah@mah.priv.at" \
        -e 'set verbose off;
        set xfer:temp-file-name *.tmp;
        set xfer:use-temp-file on;
        set ftp:use-feat false;
        set xfer:log-file /var/log/ftp-madis.log;
        connect madis-data.ncep.noaa.gov;
        mirror --parallel=2  --include-glob=*.gz /point/raob/netcdf/ /var/spool/noaa-madis/incoming;
        bye;'
````

**Comment by rs1729** [comment]
> I need to check if your observation is systematic or an intermittent error by some stations (my major maintenance job so far has been to catch corner cases in junk data coming in).

I think it is the same for all stations, e.g. station Essen (10410) in Europe:
```
WMO: 10410  SYN: 1645660800 = 2022-02-24 00:00:00 UTC  #  REL: 1645742700 = 2022-02-24 22:45:00 UTC
```
See the other stations in `20220224_0000.gz`
[stations_reltime_nc.txt.gz](https://github.com/mhaberler/radiosonde-datacollector/files/8149259/stations_reltime_nc.txt.gz)

Well, I would prefer the more detailed fm94/bufr data, but some stations offer only fm35 data.
Perhaps the wrong date in the release time is generated when the data for all the stations is put together in the netCDF file.

**Comment by rs1729** [comment]
When processing netCDF/fm35 (`netcdfutil.py`), you could consider correcting the takeoff time in geojson, e.g.
```
_takeoff = relTime
if _takeoff - synTime > 86400/2:
    _takeoff -= 86400
```
(for each `[i]`) before converting to UTC, though the takeoff and release time would not be the same anymore for 00Z soundings. However the timestamps should be more reasonable then. I'm not sure, but isn't there a time window for launches at synoptic times? I believe the difference of synoptic time and release time shouldn't be more then 3 hours, probably less. This midnight rollover bug should be reliably detectable, at least in theory.

Anyway, the issue can be closed I guess.

**Comment by mhaberler** [comment]
I applied this fix, all files post Mon Feb 28 13:40:24 CET 2022 should have the effect visible
thank you!

**Comment by mhaberler** [comment]
this one just came in and looks reasonable:   https://radiosonde.mah.priv.at/data/fm35/29/634/2022/02/29634_20220223_120000.geojson

syn_timestamp Wed Feb 23 12:00:00 UTC 2022
firstSeen Wed Feb 23 11:31:00 UTC 2022

**Comment by rs1729** [comment]
Where did you make the changes, https://github.com/mhaberler/radiosonde-datacollector/ has no new commits? Is the windy-plugin a different repo? Though the geojson-download from /app is the same data.
Last 00Z-sounding for 72208, 72208_20220301_0000Z.json,
timestamps look ok now, thanks!
```
2022-02-28 23:14:00 UTC
2022-02-28 23:14:25 UTC
[...]
2022-03-01 00:41:21 UTC
2022-03-01 00:41:21 UTC
```
"First seen" is the original "release time" I guess. This is still off, but that's ok for me.
```
Synoptic time: 2022-03-01 00:00Z (8.1 hours old)
First seen: 2022-03-01 23:14Z
```

One more request:
Can you provide the download links to the source data also on the /app-page? It is easier to access there (for me at least). I think there have been download links for source-fm35/fm94 data in the past.

**Comment by mhaberler** [comment]
right, this repo is not the code currently running - it will be eventually again, but it will take some months for reasons I'm happy to explain privately - drop me an email

the radiosonde.mah.priv.at backend service will remain open

both the server side and the client are currently being rewritten in terms of how the metadata is stored and fetched, to get rid of the humungeous summary file and have a longer history available

once this whole transition is over, I'll fix the radiosonde.mah.priv.at web app - it was never intended for general use and I am absolutely lousy at JS

if you want to go straight to a particular ascent, see the [examples](https://github.com/mhaberler/radiosonde-datacollector/tree/dev/examples) directory, which maps station id x synopticTime x format to a URL for the geojson file in Python

the [client side of the windy plugin is here](https://www.npmjs.com/package/windy-plugin-radiosonde), it has not been updated in a while tough; the author is currently busy getting it in sync with our backend changes

sorry for the rocky times 

what specifically is your use case? maybe I can help with that in another way? 

for looking at a particular ascent, the windy radiosonde plugin is the way to go as it is and will be maintained. 

For getting at the raw data, just fetch the geojson files from  radiosonde.mah.priv.at.

@rittels want to comment on the status?

**Comment by mhaberler** [comment]
hm, see the First seen: issue, looking into that

**Comment by mhaberler** [comment]
I think the firstSeen: tag is corrected now as well, for example https://radiosonde.mah.priv.at/data/station/06/060/2022/03/fm35/06060_20220301_080000.geojson

**Comment by rs1729** [comment]
I think the wrong "release time" (and "first seen") happens only if the launch time is just before midnight, i.e. the date would be the previous day compared to the date in the synoptic datetime. (I guess the date in fm35 "release time" is based on the synoptic time and not corrected for day rollover.) Thus the 08Z launch was probably ok before.

The timestamps in the latest 00Z (midnight) soundings looked good.

I don't really use the code in radiosonde-datacollector, so if you want to update when the rest of code is ready, no problem.
I download the data for particular stations if I want to compare the data to data on sondehub or the rs1729/RS decoders.
And if there is fm94 data available, I would prefer that of course.

EDIT:
here station 06060 on 2022-02-25.
```
Synoptic time: 2022-02-25 08:00Z (100.1 hours old)
First seen: 2022-02-25 07:34Z
```
08Z is ok, only 00Z is problematic.

**Comment by mhaberler** [comment]
I see

just a note re fm94:  those usually report rather high sample rates in the underlying BUFR file, like every 2 secs

I decimate those such that samples are at least 100m apart vertically - the high level of detail is useless for meteo purposes

**Comment by rs1729** [comment]
ok, good to know.
But there is also the bufr source file. That has full resolution if necessary, right?

**Comment by mhaberler** [comment]
> ok, good to know. But there is also the bufr source file. That has full resolution if necessary, right?

yes it has
